---
apiVersion: v1
kind: Service
metadata:
  name: delivery-ms
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: delivery-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
